"""
Wirestead Python bindings
"""
from __future__ import annotations
import collections.abc
import datetime
import typing
__all__: list[str] = ['AccessDenied', 'AlreadyConnected', 'BackpressureStrategy', 'BestEffort', 'ConnectionAborted', 'ConnectionContext', 'ConnectionRefused', 'ConnectionReset', 'ErrorCode', 'ErrorContext', 'IFramer', 'InternalError', 'InvalidConfiguration', 'IoError', 'LineFramer', 'MessageContext', 'NotConnected', 'PacketFramer', 'PortInUse', 'Reliable', 'RuntimeStats', 'Serial', 'StartFailed', 'Stopped', 'Success', 'TcpClient', 'TcpServer', 'TimedOut', 'UdpClient', 'UdpConfig', 'UdpServer', 'UdsClient', 'UdsServer', 'Unknown']
class BackpressureStrategy:
    """
    Members:
    
      Reliable
    
      BestEffort
    """
    BestEffort: typing.ClassVar[BackpressureStrategy]  # value = <BackpressureStrategy.BestEffort: 1>
    Reliable: typing.ClassVar[BackpressureStrategy]  # value = <BackpressureStrategy.Reliable: 0>
    __members__: typing.ClassVar[dict[str, BackpressureStrategy]]  # value = {'Reliable': <BackpressureStrategy.Reliable: 0>, 'BestEffort': <BackpressureStrategy.BestEffort: 1>}
    @typing.overload
    def __eq__(self, other: BackpressureStrategy) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: BackpressureStrategy) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class ConnectionContext:
    @property
    def client_id(self) -> int:
        ...
    @property
    def client_info(self) -> str:
        ...
class ErrorCode:
    """
    Members:
    
      Success
    
      Unknown
    
      InvalidConfiguration
    
      InternalError
    
      IoError
    
      ConnectionRefused
    
      ConnectionReset
    
      ConnectionAborted
    
      TimedOut
    
      NotConnected
    
      AlreadyConnected
    
      PortInUse
    
      AccessDenied
    
      Stopped
    
      StartFailed
    """
    AccessDenied: typing.ClassVar[ErrorCode]  # value = <ErrorCode.AccessDenied: 12>
    AlreadyConnected: typing.ClassVar[ErrorCode]  # value = <ErrorCode.AlreadyConnected: 10>
    ConnectionAborted: typing.ClassVar[ErrorCode]  # value = <ErrorCode.ConnectionAborted: 7>
    ConnectionRefused: typing.ClassVar[ErrorCode]  # value = <ErrorCode.ConnectionRefused: 5>
    ConnectionReset: typing.ClassVar[ErrorCode]  # value = <ErrorCode.ConnectionReset: 6>
    InternalError: typing.ClassVar[ErrorCode]  # value = <ErrorCode.InternalError: 3>
    InvalidConfiguration: typing.ClassVar[ErrorCode]  # value = <ErrorCode.InvalidConfiguration: 2>
    IoError: typing.ClassVar[ErrorCode]  # value = <ErrorCode.IoError: 4>
    NotConnected: typing.ClassVar[ErrorCode]  # value = <ErrorCode.NotConnected: 9>
    PortInUse: typing.ClassVar[ErrorCode]  # value = <ErrorCode.PortInUse: 11>
    StartFailed: typing.ClassVar[ErrorCode]  # value = <ErrorCode.StartFailed: 14>
    Stopped: typing.ClassVar[ErrorCode]  # value = <ErrorCode.Stopped: 13>
    Success: typing.ClassVar[ErrorCode]  # value = <ErrorCode.Success: 0>
    TimedOut: typing.ClassVar[ErrorCode]  # value = <ErrorCode.TimedOut: 8>
    Unknown: typing.ClassVar[ErrorCode]  # value = <ErrorCode.Unknown: 1>
    __members__: typing.ClassVar[dict[str, ErrorCode]]  # value = {'Success': <ErrorCode.Success: 0>, 'Unknown': <ErrorCode.Unknown: 1>, 'InvalidConfiguration': <ErrorCode.InvalidConfiguration: 2>, 'InternalError': <ErrorCode.InternalError: 3>, 'IoError': <ErrorCode.IoError: 4>, 'ConnectionRefused': <ErrorCode.ConnectionRefused: 5>, 'ConnectionReset': <ErrorCode.ConnectionReset: 6>, 'ConnectionAborted': <ErrorCode.ConnectionAborted: 7>, 'TimedOut': <ErrorCode.TimedOut: 8>, 'NotConnected': <ErrorCode.NotConnected: 9>, 'AlreadyConnected': <ErrorCode.AlreadyConnected: 10>, 'PortInUse': <ErrorCode.PortInUse: 11>, 'AccessDenied': <ErrorCode.AccessDenied: 12>, 'Stopped': <ErrorCode.Stopped: 13>, 'StartFailed': <ErrorCode.StartFailed: 14>}
    @typing.overload
    def __eq__(self, other: ErrorCode) -> bool:
        ...
    @typing.overload
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    @typing.overload
    def __ne__(self, other: ErrorCode) -> bool:
        ...
    @typing.overload
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class ErrorContext:
    @property
    def client_id(self) -> int | None:
        ...
    @property
    def code(self) -> ErrorCode:
        ...
    @property
    def message(self) -> str:
        ...
class IFramer:
    pass
class LineFramer(IFramer):
    def __init__(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> None:
        ...
    def reset(self) -> None:
        ...
class MessageContext:
    def __buffer__(self, flags):
        """
        Return a buffer object that exposes the underlying memory of the object.
        """
    def __release_buffer__(self, buffer):
        """
        Release the buffer object that exposes the underlying memory of the object.
        """
    @property
    def client_id(self) -> int:
        ...
    @property
    def client_info(self) -> str:
        ...
    @property
    def data(self) -> bytes:
        ...
class PacketFramer(IFramer):
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def reset(self) -> None:
        ...
class RuntimeStats:
    def __repr__(self) -> str:
        ...
    @property
    def backpressure_active(self) -> bool:
        ...
    @property
    def backpressure_events(self) -> int:
        ...
    @property
    def bytes_accepted(self) -> int:
        ...
    @property
    def bytes_received(self) -> int:
        ...
    @property
    def bytes_sent(self) -> int:
        ...
    @property
    def dropped_bytes(self) -> int:
        ...
    @property
    def dropped_messages(self) -> int:
        ...
    @property
    def failed_sends(self) -> int:
        ...
    @property
    def max_queued_bytes(self) -> int:
        ...
    @property
    def messages_accepted(self) -> int:
        ...
    @property
    def messages_received(self) -> int:
        ...
    @property
    def messages_sent(self) -> int:
        ...
    @property
    def pending_bytes(self) -> int:
        ...
    @property
    def queued_bytes(self) -> int:
        ...
class Serial:
    backpressure_strategy: BackpressureStrategy
    def __init__(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def auto_start(self, start: bool = True) -> Serial:
        ...
    def baud_rate(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> Serial:
        ...
    def connected(self) -> bool:
        ...
    def data_bits(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> Serial:
        ...
    def flow_control(self, arg0: str) -> Serial:
        ...
    def on_backpressure(self, arg0: collections.abc.Callable[[int], None]) -> Serial:
        ...
    def on_connect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> Serial:
        ...
    def on_data(self, arg0: collections.abc.Callable[[MessageContext], None]) -> Serial:
        ...
    def on_data_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> Serial:
        ...
    def on_disconnect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> Serial:
        ...
    def on_error(self, arg0: collections.abc.Callable[[ErrorContext], None]) -> Serial:
        ...
    def on_message(self, arg0: collections.abc.Callable[[MessageContext], None]) -> Serial:
        ...
    def on_message_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> Serial:
        ...
    def parity(self, arg0: str) -> Serial:
        ...
    def reset_stats(self) -> None:
        ...
    def retry_interval(self, arg0: datetime.timedelta) -> Serial:
        ...
    def send(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def send_line(self, arg0: str) -> bool:
        ...
    def start(self) -> bool:
        ...
    def start_sync(self) -> bool:
        ...
    def stats(self) -> RuntimeStats:
        ...
    def stop(self) -> None:
        ...
    def stop_bits(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> Serial:
        ...
    def use_line_framer(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> Serial:
        ...
    def use_packet_framer(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> Serial:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class TcpClient:
    backpressure_strategy: BackpressureStrategy
    def __init__(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def auto_start(self, start: bool = True) -> TcpClient:
        ...
    def batch_latency(self, arg0: datetime.timedelta) -> TcpClient:
        ...
    def batch_size(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> TcpClient:
        ...
    def connected(self) -> bool:
        ...
    def connection_timeout(self, arg0: datetime.timedelta) -> TcpClient:
        ...
    def max_retries(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> TcpClient:
        ...
    def on_backpressure(self, arg0: collections.abc.Callable[[int], None]) -> TcpClient:
        ...
    def on_connect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> TcpClient:
        ...
    def on_data(self, arg0: collections.abc.Callable[[MessageContext], None]) -> TcpClient:
        ...
    def on_data_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> TcpClient:
        ...
    def on_disconnect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> TcpClient:
        ...
    def on_error(self, arg0: collections.abc.Callable[[ErrorContext], None]) -> TcpClient:
        ...
    def on_message(self, arg0: collections.abc.Callable[[MessageContext], None]) -> TcpClient:
        ...
    def on_message_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> TcpClient:
        ...
    def reset_stats(self) -> None:
        ...
    def retry_interval(self, arg0: datetime.timedelta) -> TcpClient:
        ...
    def send(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def send_blocking(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def send_line(self, arg0: str) -> bool:
        ...
    def start(self) -> bool:
        ...
    def start_sync(self) -> bool:
        ...
    def stats(self) -> RuntimeStats:
        ...
    def stop(self) -> None:
        ...
    def use_line_framer(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> TcpClient:
        ...
    def use_packet_framer(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> TcpClient:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class TcpServer:
    backpressure_strategy: BackpressureStrategy
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def auto_start(self, start: bool = True) -> TcpServer:
        ...
    def bind_address(self, arg0: str) -> TcpServer:
        ...
    def broadcast(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def client_count(self) -> int:
        ...
    def connected_clients(self) -> list[int]:
        ...
    def idle_timeout(self, arg0: datetime.timedelta) -> TcpServer:
        ...
    def listening(self) -> bool:
        ...
    def max_clients(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> TcpServer:
        ...
    def on_backpressure(self, arg0: collections.abc.Callable[[int], None]) -> TcpServer:
        ...
    def on_connect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> TcpServer:
        ...
    def on_data(self, arg0: collections.abc.Callable[[MessageContext], None]) -> TcpServer:
        ...
    def on_data_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> TcpServer:
        ...
    def on_disconnect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> TcpServer:
        ...
    def on_error(self, arg0: collections.abc.Callable[[ErrorContext], None]) -> TcpServer:
        ...
    def on_message(self, arg0: collections.abc.Callable[[MessageContext], None]) -> TcpServer:
        ...
    def on_message_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> TcpServer:
        ...
    def port_retry(self, enable: bool = True, max_retries: typing.SupportsInt | typing.SupportsIndex = 3, retry_interval_ms: typing.SupportsInt | typing.SupportsIndex = 1000) -> TcpServer:
        ...
    def reset_stats(self) -> None:
        ...
    def send_to(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: collections.abc.Buffer) -> bool:
        ...
    def start(self) -> bool:
        ...
    def start_sync(self) -> bool:
        ...
    def stats(self) -> RuntimeStats:
        ...
    def stop(self) -> None:
        ...
    def use_line_framer(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> TcpServer:
        ...
    def use_packet_framer(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> TcpServer:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class UdpClient:
    backpressure_strategy: BackpressureStrategy
    def __init__(self, arg0: UdpConfig) -> None:
        ...
    def auto_start(self, start: bool = True) -> UdpClient:
        ...
    def connected(self) -> bool:
        ...
    def on_backpressure(self, arg0: collections.abc.Callable[[int], None]) -> UdpClient:
        ...
    def on_connect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdpClient:
        ...
    def on_data(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdpClient:
        ...
    def on_data_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdpClient:
        ...
    def on_disconnect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdpClient:
        ...
    def on_error(self, arg0: collections.abc.Callable[[ErrorContext], None]) -> UdpClient:
        ...
    def on_message(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdpClient:
        ...
    def on_message_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdpClient:
        ...
    def reset_stats(self) -> None:
        ...
    def send(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def send_line(self, arg0: str) -> bool:
        ...
    def start(self) -> bool:
        ...
    def start_sync(self) -> bool:
        ...
    def stats(self) -> RuntimeStats:
        ...
    def stop(self) -> None:
        ...
    def use_line_framer(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> UdpClient:
        ...
    def use_packet_framer(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> UdpClient:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class UdpConfig:
    backpressure_strategy: BackpressureStrategy
    bind_address: str
    enable_memory_pool: bool
    remote_address: str | None
    stop_on_callback_exception: bool
    def __init__(self) -> None:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def local_port(self) -> int:
        ...
    @local_port.setter
    def local_port(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def remote_port(self) -> int | None:
        ...
    @remote_port.setter
    def remote_port(self, arg0: typing.SupportsInt | typing.SupportsIndex | None) -> None:
        ...
class UdpServer:
    backpressure_strategy: BackpressureStrategy
    @typing.overload
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: UdpConfig) -> None:
        ...
    def auto_start(self, start: bool = True) -> UdpServer:
        ...
    def broadcast(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def client_count(self) -> int:
        ...
    def connected_clients(self) -> list[int]:
        ...
    def idle_timeout(self, arg0: datetime.timedelta) -> UdpServer:
        ...
    def listening(self) -> bool:
        ...
    def max_clients(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> UdpServer:
        ...
    def on_backpressure(self, arg0: collections.abc.Callable[[int], None]) -> UdpServer:
        ...
    def on_connect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdpServer:
        ...
    def on_data(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdpServer:
        ...
    def on_data_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdpServer:
        ...
    def on_disconnect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdpServer:
        ...
    def on_error(self, arg0: collections.abc.Callable[[ErrorContext], None]) -> UdpServer:
        ...
    def on_message(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdpServer:
        ...
    def on_message_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdpServer:
        ...
    def reset_stats(self) -> None:
        ...
    def send_to(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: collections.abc.Buffer) -> bool:
        ...
    def start(self) -> bool:
        ...
    def start_sync(self) -> bool:
        ...
    def stats(self) -> RuntimeStats:
        ...
    def stop(self) -> None:
        ...
    def use_line_framer(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> UdpServer:
        ...
    def use_packet_framer(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> UdpServer:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class UdsClient:
    backpressure_strategy: BackpressureStrategy
    def __init__(self, arg0: str) -> None:
        ...
    def auto_start(self, start: bool = True) -> UdsClient:
        ...
    def connected(self) -> bool:
        ...
    def connection_timeout(self, arg0: datetime.timedelta) -> UdsClient:
        ...
    def max_retries(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> UdsClient:
        ...
    def on_backpressure(self, arg0: collections.abc.Callable[[int], None]) -> UdsClient:
        ...
    def on_connect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdsClient:
        ...
    def on_data(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdsClient:
        ...
    def on_data_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdsClient:
        ...
    def on_disconnect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdsClient:
        ...
    def on_error(self, arg0: collections.abc.Callable[[ErrorContext], None]) -> UdsClient:
        ...
    def on_message(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdsClient:
        ...
    def on_message_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdsClient:
        ...
    def reset_stats(self) -> None:
        ...
    def retry_interval(self, arg0: datetime.timedelta) -> UdsClient:
        ...
    def send(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def send_line(self, arg0: str) -> bool:
        ...
    def start(self) -> bool:
        ...
    def start_sync(self) -> bool:
        ...
    def stats(self) -> RuntimeStats:
        ...
    def stop(self) -> None:
        ...
    def use_line_framer(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> UdsClient:
        ...
    def use_packet_framer(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> UdsClient:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class UdsServer:
    backpressure_strategy: BackpressureStrategy
    def __init__(self, arg0: str) -> None:
        ...
    def auto_start(self, start: bool = True) -> UdsServer:
        ...
    def broadcast(self, arg0: collections.abc.Buffer) -> bool:
        ...
    def client_count(self) -> int:
        ...
    def connected_clients(self) -> list[int]:
        ...
    def idle_timeout(self, arg0: datetime.timedelta) -> UdsServer:
        ...
    def listening(self) -> bool:
        ...
    def max_clients(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> UdsServer:
        ...
    def on_backpressure(self, arg0: collections.abc.Callable[[int], None]) -> UdsServer:
        ...
    def on_connect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdsServer:
        ...
    def on_data(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdsServer:
        ...
    def on_data_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdsServer:
        ...
    def on_disconnect(self, arg0: collections.abc.Callable[[ConnectionContext], None]) -> UdsServer:
        ...
    def on_error(self, arg0: collections.abc.Callable[[ErrorContext], None]) -> UdsServer:
        ...
    def on_message(self, arg0: collections.abc.Callable[[MessageContext], None]) -> UdsServer:
        ...
    def on_message_batch(self, arg0: collections.abc.Callable[[list[MessageContext]], None]) -> UdsServer:
        ...
    def reset_stats(self) -> None:
        ...
    def send_to(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: collections.abc.Buffer) -> bool:
        ...
    def start(self) -> bool:
        ...
    def start_sync(self) -> bool:
        ...
    def stats(self) -> RuntimeStats:
        ...
    def stop(self) -> None:
        ...
    def use_line_framer(self, delimiter: str = '\n', include_delimiter: bool = False, max_length: typing.SupportsInt | typing.SupportsIndex = 65536) -> UdsServer:
        ...
    def use_packet_framer(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg2: typing.SupportsInt | typing.SupportsIndex) -> UdsServer:
        ...
    @property
    def backpressure_threshold(self) -> int:
        ...
    @backpressure_threshold.setter
    def backpressure_threshold(self, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
AccessDenied: ErrorCode  # value = <ErrorCode.AccessDenied: 12>
AlreadyConnected: ErrorCode  # value = <ErrorCode.AlreadyConnected: 10>
BestEffort: BackpressureStrategy  # value = <BackpressureStrategy.BestEffort: 1>
ConnectionAborted: ErrorCode  # value = <ErrorCode.ConnectionAborted: 7>
ConnectionRefused: ErrorCode  # value = <ErrorCode.ConnectionRefused: 5>
ConnectionReset: ErrorCode  # value = <ErrorCode.ConnectionReset: 6>
InternalError: ErrorCode  # value = <ErrorCode.InternalError: 3>
InvalidConfiguration: ErrorCode  # value = <ErrorCode.InvalidConfiguration: 2>
IoError: ErrorCode  # value = <ErrorCode.IoError: 4>
NotConnected: ErrorCode  # value = <ErrorCode.NotConnected: 9>
PortInUse: ErrorCode  # value = <ErrorCode.PortInUse: 11>
Reliable: BackpressureStrategy  # value = <BackpressureStrategy.Reliable: 0>
StartFailed: ErrorCode  # value = <ErrorCode.StartFailed: 14>
Stopped: ErrorCode  # value = <ErrorCode.Stopped: 13>
Success: ErrorCode  # value = <ErrorCode.Success: 0>
TimedOut: ErrorCode  # value = <ErrorCode.TimedOut: 8>
Unknown: ErrorCode  # value = <ErrorCode.Unknown: 1>
__version__: str = '0.9.6'
